server:
  port: 8080
  servlet:
    context-path: /potato-api

spring:
  application:
    name: potato-api
  datasource:
    url: "jdbc:mysql://root:hEADBsutIDCHrAVXQxORzhXxXvCbvaFv@shinkansen.proxy.rlwy.net:22984/railway"
    username: root
    password: hEADBsutIDCHrAVXQxORzhXxXvCbvaFv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true